baseURL: "https://mwisniewski.pl/"
languageCode: "en-us"
title: "Michal Wisniewski"
theme: "hugo-profile"
relativeURLs: true

googleanalytics: UA-126456967-1
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "Software Developer"

  # home
  disable_home: false
  profile_image: "/images/photo.png"
  name: "Michal Wisniewski"
  profession: "Software Developer"
  github: "https://github.com/sofalse"
  linkedin: "https://www.linkedin.com/in/mwisn/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm a fullstack software developer based in Poland. I have firm experience with fintech projects, as well as with retail and Internet of Things."
  descripe_l2_person: "You can find projects I worked on [here](#projects). Project names are hidden because of NDA."
  skills:
    - name: JavaScript/TypeScript
      percentage: 100
    - name: React
      percentage: 90
    - name: Docker/kubernetes
      percentage: 80
    - name: AWS
      percentage: 85
    - name: Unit Testing
      percentage: 80

  # Experience
  disable_experience: false
  experience:
    - company: "Netguru"
      id: "netguru"
      role: "Software Developer"
      startdate: July 2018
      enddate: October 2019
      featuredpoints:
        - point: Fullstack development in React and NodeJS + TypeScript
        - point: Conducting technical recruitments
        - point: Maintaining and developing AWS architecture
        - point: Performing code review and updating CI flows
        - point: Creating and enhancing microservices running on Serverless architecture
        - point: Writing database migrations
        - point: Keeping documentation up-to-date
    - company: "SoftServe"
      id: "softserve"
      role: "Senior Software Developer"
      startdate: October 2019
      enddate: present
      featuredpoints:
        - point: Fullstack development in React and NodeJS (Microservice architecture)
        - point: Creating financial graphs and dashboards using d3 library
        - point: Performing code review and updating CI flows
        - point: Evolving the project from PoC to the market-ready solution level
        - point: Writing database migrations

  # Education
  disable_education: true
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Financial Consulting Company"
      img: /images/project.jpg
      description: "Fullstack development of a dashboard used for tracking investments. Microservice, containerized architecture on AWS, kubernetes orchestration. Backend in NodeJS, frontend in React with extensive use of 3d library (for graphs)."
    - name: "Berlin Fintech Startup"
      img: /images/project.jpg
      description: "Fullstack development of a fintech application used for capital investments. Microservice architecture on AWS, Agile methodology."
    - name: "UK Retail Network"
      img: /images/project.jpg
      description: "Backend development for a british retail network."
    - name: "Local Enterpreneur"
      img: /images/project.jpg
      description: "Backend development of a Internet of Things project - automatic beer brewing machine. With usage of Raspberry Pi and external sensors. Code written in TypeScript."

  # Achievements
  disable_achievements: false
  achievements:
    - title: AWS Certified Cloud Practitioner
      description: Issued on Oct 23 2020
      img: /images/AWS-CP.png
      link: https://www.credly.com/badges/6fd626ed-f6cb-4d42-a44f-09b326073d3f/public_url

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "michal.wisniewski@mwisniewski.pl"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
